#!/bin/bash

clear

if [ $# == 0 ]; then     # if no arguments provided, prompt user
    echo -n “What command(s) are you asking about?> “
    read args
else
    args=$*
fi

for cmd in `echo $args`  # for each command entered
do
    echo “$cmd”
    echo -n “executable: “
    which $cmd
    echo -n “all files: “
    whereis $cmd | sed “s/$cmd: //“
    echo “function(s):”
    whatis $cmd
    echo “====================================================================”
done