#!/bin/bash

# Check if git is installed
if ! command -v git &> /dev/null; then
    echo "Git is not installed. Please install Git and try again."
    exit 1
else
    echo "Git is installed."
    
    git version

    git config --global init.defaultBranch ${GITHUB_INIT_DEFAULT_BRANCH}
    git config --global user.email ${GITHUB_USER_EMAIL}
    git config --global user.name ${GITHUB_USER_NAME}

    git config --list
fi
