#!/bin/bash

# Check if git is installed
if ! command -v git &> /dev/null; then
    echo "Git is not installed. Please install Git and try again."
    exit 1
else
    echo "Git is installed."
    
    git version

    git config --global init.defaultBranch main
    git config --global user.email "173560+spr12ian@users.noreply.github.com"
    git config --global user.name "spr12ian"

    git config --list
fi