#!/bin/bash
# This may not be needed if running Linux under Windows Subsystem for Linux (WSL)
curl -L "https://go.microsoft.com/fwlink/?LinkID=760868" > vscode.deb
sudo apt install -y ./vscode.deb
rm vscode.deb
