#!/bin/bash

if [ -d .git ]; then 
  echo ".git folder exists"
# git rm -r --cached . 
# git add .
# git commit -m 'Removed all files that are in the .gitignore' 
# git push origin main
else
  echo ".git folder does not exist"
fi